# Generated by Django 3.2.11 on 2022-03-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='value',
            old_name='date_created',
            new_name='timestamp',
        ),
    ]
